### PR TITLE
Question behavior working with mock repository

### LINKED ISSUE #10: Add question activity behavior
Add basic behavior to question activity:
* If guess the question, return to Roulette view to select new questions
* If fails the question, go to wait view and pass the turn to the next player

### PR DESCRIPTION
**Pull request by pedrodaviddev**
Close #10

### CODE REVIEW

File: app/src/main/java/com/pedrodavidlp/ittrivial/game/contract/QuestionContract.kt [hunk 1]
```diff
@@ -11,7 +11,7 @@ class QuestionContract {
   interface Presenter {
     fun init()
     fun setView(view: View)
-    fun onLogin(username: String)
+    fun getQuestion()
```
Comment (bytemines) [inline app/src/main/java/com/pedrodavidlp/ittrivial/game/contract/QuestionContract.kt:14]: question or questions?

File: app/src/main/java/com/pedrodavidlp/ittrivial/game/presenter/QuestionPresenter.kt [hunk 2]
```diff
@@ -0,0 +1,39 @@
+package com.pedrodavidlp.ittrivial.game.presenter
+
+import com.pedrodavidlp.ittrivial.game.contract.QuestionContract
+import com.pedrodavidlp.ittrivial.game.domain.model.Question
+import com.pedrodavidlp.ittrivial.game.domain.repository.QuestionRepository
+import com.pedrodavidlp.ittrivial.game.router.QuestionRouter
+
+class QuestionPresenter(val repository: QuestionRepository, val router: QuestionRouter) :
+    QuestionContract.Presenter, QuestionContract.InteractorOutput {
+  lateinit var viper: QuestionContract.View
```
Comment (bytemines) [inline app/src/main/java/com/pedrodavidlp/ittrivial/game/presenter/QuestionPresenter.kt:10]: WTF, this is the view not a Viper var

**Review by bytemines — APPROVED** [review]
